package financialmarketsimulator.market;

import financialmarketsimulator.exception.NotEnoughDataException;
import financialmarketsimulator.strategies.Phantom;
import java.io.IOException;
import javax.swing.JList;

/**
 * @brief The Phantom Market Participant is a special type of MarketParticipant,
 * it is used to start trading and generating so that other strategies may use
 * the data generated by it to trade based on their strategies.
 * @author Grape <cos301.mainproject.grape@gmail.com>
 */
public class PhantomMarketParticipant extends MarketParticipant {

    public static enum LEVEL_SHARES {

        LOW, HIGH, MEDIUM
    };

    public static enum LEVEL_PRICE {

        LOW, HIGH, MEDIUM
    };

    public PhantomMarketParticipant(String participantName, String participantID, MarketExchange exchange, String stock) throws NotEnoughDataException, IOException {
        super(participantName, participantID, exchange, stock, new Phantom());
    }
}
