/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package simulatorInterface;

import financialmarketsimulator.exception.NotEnoughDataException;
import financialmarketsimulator.market.MarketExchange;
import financialmarketsimulator.market.MarketParticipant;
import financialmarketsimulator.market.MarketStrategy;
import financialmarketsimulator.market.PhantomMarketParticipant;
import financialmarketsimulator.market.StockManager;
import financialmarketsimulator.strategies.DirectionalMovementIndex;
import financialmarketsimulator.strategies.MACDStrategy;
import financialmarketsimulator.strategies.MovingAverageCrossover;
import financialmarketsimulator.strategies.MovingAverageEnvelope;
import financialmarketsimulator.strategies.MovingAverageFilter;
import financialmarketsimulator.strategies.Phantom;
import financialmarketsimulator.strategies.PriceEmaCrossover;
import financialmarketsimulator.strategies.PriceSmaCrossover;
import financialmarketsimulator.strategies.SimpleRSI;
import financialmarketsimulator.strategies.Simple_MACD_ADX;
import java.awt.Cursor;
import java.awt.Frame;
import static java.awt.Frame.getFrames;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.ldap.ManageReferralControl;
import javax.swing.DefaultListModel;

/**
 *
 * @author Siphe
 */
public class Participants extends javax.swing.JFrame {

    ArrayList<MarketParticipant> participants = new ArrayList();
    MarketExchange exchange = MarketExchange.getInstance("JSE");

    /**
     * Creates new form Participants
     */
    public Participants() {
        initComponents();
        Frame[] frames = getFrames();

        if (frames.length > 0) {
            frames[0].setResizable(false);
        }

        Cursor cursor = Cursor.getDefaultCursor();
        //change cursor appearance to HAND_CURSOR when the mouse pointed on images
        cursor = Cursor.getPredefinedCursor(Cursor.HAND_CURSOR);
        setCursor(cursor);

        Map<String, StockManager> mang = exchange.getStocksManagers();

        for (StockManager val : mang.values()) {
            cbxStocks.addItem(val.getStockName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnGenerateParticipants = new javax.swing.JButton();
        cbxStrategies = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cbxStocks = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lbxParticipantList = new javax.swing.JList();
        jLabel6 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        btnGenerateParticipants1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Select Participants");
        jLabel1.setToolTipText("Select Market Participants to trade");

        jButton1.setBackground(new java.awt.Color(0, 0, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 255, 0));
        jButton1.setText("Load");
        jButton1.setToolTipText("Create custom Market Participant");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnGenerateParticipants.setBackground(new java.awt.Color(0, 0, 204));
        btnGenerateParticipants.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnGenerateParticipants.setForeground(new java.awt.Color(0, 255, 0));
        btnGenerateParticipants.setText("Generate Participants");
        btnGenerateParticipants.setToolTipText("Create custom Market Participant");
        btnGenerateParticipants.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGenerateParticipants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateParticipantsActionPerformed(evt);
            }
        });

        cbxStrategies.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MACDStrategy", "DirectionalMovementIndex", "MovingAverageCrossover", "MovingAverageEnvelope", "MovingAverageFilter", "PriceEmaCrossover", "PriceSmaCrossover", "SimpleRSI", "Simple_MACD_ADX", "Phantom" }));

        jLabel2.setText("Strategy:");

        jLabel3.setText("Stock:");

        jLabel4.setText("Name:");

        jLabel5.setText("ID:");

        jButton3.setBackground(new java.awt.Color(153, 255, 153));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("NEXT -->");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(153, 255, 153));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("<-- BACK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(lbxParticipantList);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Added Participants");

        jButton5.setBackground(new java.awt.Color(0, 0, 204));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 255, 0));
        jButton5.setText("Add Participant");
        jButton5.setToolTipText("Create custom Market Participant");
        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        btnGenerateParticipants1.setBackground(new java.awt.Color(0, 0, 204));
        btnGenerateParticipants1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnGenerateParticipants1.setForeground(new java.awt.Color(0, 255, 0));
        btnGenerateParticipants1.setText("Clear All");
        btnGenerateParticipants1.setToolTipText("Create custom Market Participant");
        btnGenerateParticipants1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGenerateParticipants1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateParticipants1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(133, 133, 133))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnGenerateParticipants, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnGenerateParticipants1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(cbxStrategies, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel5)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel4)
                                                        .addComponent(jLabel3))
                                                    .addGap(34, 34, 34)
                                                    .addComponent(cbxStocks, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(1, 1, 1)))))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxStocks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxStrategies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGenerateParticipants, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGenerateParticipants1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnGenerateParticipantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateParticipantsActionPerformed

        btnGenerateParticipants.setEnabled(false);

        if (exchange.getStocksManagers().size() <= 0) {
            MessageBox.infoBox("Automatic stock generated, \"INV\"", "No Stocks found");
            exchange.addStockManager(new StockManager("INV"));
        } else {
            for (StockManager manager : exchange.getStocksManagers().values()) {
                if (manager == null) {
                    System.out.println("Manager does not exist.");
                    return;
                }

                try {
                    MarketStrategy strategy1 = new DirectionalMovementIndex(exchange.getBook(manager.getStockName()), 14);
                    MarketStrategy strategy2 = new MovingAverageCrossover(exchange.getBook(manager.getStockName()), 14);
                    MarketStrategy strategy3 = new MovingAverageEnvelope(exchange.getBook(manager.getStockName()));
                    MarketStrategy strategy4 = new MovingAverageFilter(exchange.getBook(manager.getStockName()), 14);
                    MarketStrategy strategy5 = new PriceEmaCrossover(exchange, exchange.getBook(manager.getStockName()), 14);
                    MarketStrategy strategy6 = new PriceSmaCrossover(exchange, exchange.getBook(manager.getStockName()), 14);
                    MarketStrategy strategy7 = new SimpleRSI(exchange.getBook(manager.getStockName()));
                    MarketStrategy strategy8 = new Simple_MACD_ADX(exchange.getBook(manager.getStockName()));
                    MarketStrategy strategy9 = new MACDStrategy(exchange.getBook(manager.getStockName()));

                    MarketParticipant mp1 = new MarketParticipant("Participant 1 " + strategy1.getStrategyName(), "1", exchange, manager.getStockName(), strategy1);
                    manager.attach(mp1);
                    participants.add(mp1);

                    MarketParticipant mp2 = new MarketParticipant("Participant 2 " + strategy2.getStrategyName(), "2", exchange, manager.getStockName(), strategy2);
                    manager.attach(mp2);
                    participants.add(mp2);

                    MarketParticipant mp3 = new MarketParticipant("Participant 3 " + strategy3.getStrategyName(), "3", exchange, manager.getStockName(), strategy3);
                    manager.attach(mp3);
                    participants.add(mp3);

                    MarketParticipant mp4 = new MarketParticipant("Participant 4 " + strategy4.getStrategyName(), "4", exchange, manager.getStockName(), strategy4);
                    manager.attach(mp4);
                    participants.add(mp4);

                    MarketParticipant mp5 = new MarketParticipant("Participant 5 " + strategy5.getStrategyName(), "5", exchange, manager.getStockName(), strategy5);
                    manager.attach(mp5);
                    participants.add(mp5);

                    MarketParticipant mp6 = new MarketParticipant("Participant 6 " + strategy6.getStrategyName(), "6", exchange, manager.getStockName(), strategy6);
                    manager.attach(mp6);
                    participants.add(mp6);

                    MarketParticipant mp7 = new MarketParticipant("Participant 7 " + strategy7.getStrategyName(), "7", exchange, manager.getStockName(), strategy7);
                    manager.attach(mp7);
                    participants.add(mp7);

                    MarketParticipant mp8 = new MarketParticipant("Participant 8 " + strategy8.getStrategyName(), "8", exchange, manager.getStockName(), strategy8);
                    manager.attach(mp8);
                    participants.add(mp8);

                    MarketParticipant mp9 = new MarketParticipant("Participant 9 " + strategy9.getStrategyName(), "9", exchange, manager.getStockName(), strategy9);
                    manager.attach(mp9);
                    participants.add(mp9);

                } catch (NotEnoughDataException e) {
                } catch (Exception ee) {
                }
            }
        }

        DefaultListModel model = new DefaultListModel();

        for (MarketParticipant part : participants) {
            model.addElement(part.toString());
        }

        lbxParticipantList.setModel(model);
    }//GEN-LAST:event_btnGenerateParticipantsActionPerformed
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        if (participants.size() <= 0) {
            MessageBox.infoBox("No Participants were added", "No Participants added");
            return;
        }

        for (MarketParticipant marketParticipant : participants) {
            StockManager manager = exchange.getManager(marketParticipant.getStock());
            if (manager == null) {
                MessageBox.infoBox("Stock Manager does not exist for specified stock", "Invalid Stock");
                return;
            }
            manager.attach(marketParticipant);
        }

        for (StockManager manager : exchange.getStocksManagers().values()) {
            if (manager.getAllParticipantsForStock().size() > 0) {
                try {
                    manager.attach(new PhantomMarketParticipant("Phantom", "Phantom", exchange, manager.getStockName()));

                } catch (NotEnoughDataException ex) {
                    Logger.getLogger(Participants.class
                            .getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Participants.class
                            .getName()).log(Level.SEVERE, null, ex);
                }
            }
        }

        dispose();

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RunSimulation.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RunSimulation.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RunSimulation.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RunSimulation.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RunSimulation().setVisible(true);
            }
        });
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        dispose();

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stocks.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stocks.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stocks.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stocks.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stocks().setVisible(true);
            }
        });
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        MarketStrategy strategy = null;

        String strat = cbxStrategies.getSelectedItem().toString().trim();
        String stockName = cbxStocks.getSelectedItem().toString().trim();
        String partName = txtName.getText().trim();
        String ID = txtID.getText().trim();

        if ("".equals(strat)) {
            MessageBox.infoBox("Please select a strategy", "No Strategy Selected");
            return;
        } else if ("".equals(stockName)) {
            MessageBox.infoBox("Please select a stock", "No Stock Selected");
            return;
        } else if ("".equals(ID) || "".equals(partName)) {
            MessageBox.infoBox("Please enter Name and ID", "Missing fields");
            return;
        } else if (!exchange.stockFound(stockName)) {
            MessageBox.infoBox("Selected stock does not exist please create it.", "Stock not Found");
            return;
        }

        for (MarketParticipant part : participants) {
            if (part.getParticipantID().equals(ID) && part.getStock().equals(stockName)) {
                MessageBox.infoBox("Market Participant ID's must be unique", "Duplicate ID's found");
                return;
            }
        }

        switch (strat) {
            case "Phantom":
                strategy = new Phantom();
                break;
            case "DirectionalMovementIndex":
                strategy = new DirectionalMovementIndex(exchange.getBook(stockName), 14);
                break;
            case "MACDStrategy":
                try {
                    strategy = new MACDStrategy(exchange.getBook(stockName));
                } catch (NotEnoughDataException ex) {
                    MessageBox.infoBox("Insufficient Data to create MACD Strategy", "");
                }
                break;
            case "MovingAverageCrossover":
                try {
                    strategy = new MovingAverageCrossover(exchange.getBook(stockName), 14);
                } catch (NotEnoughDataException ex) {
                    MessageBox.infoBox("Insufficient Data to create MovingAverageCrossover Strategy", "");
                }
                break;
            case "MovingAverageEnvelope":
                try {
                    strategy = new MovingAverageEnvelope(exchange.getBook(stockName));
                } catch (NotEnoughDataException ex) {
                    MessageBox.infoBox("Insufficient Data to create Moving Average Envelope Strategy", "");
                }
                break;
            case "MovingAverageFilter":
                try {
                    strategy = new MovingAverageFilter(exchange.getBook(stockName), 14);
                } catch (NotEnoughDataException ex) {
                    MessageBox.infoBox("Insufficient Data to create Moving Average Filter Strategy", "");
                }
                break;
            case "PriceEmaCrossover":
                try {
                    strategy = new PriceEmaCrossover(exchange, exchange.getBook(stockName), 14);
                } catch (NotEnoughDataException ex) {
                    MessageBox.infoBox("Insufficient Data to create Price EMA Crossover Strategy", "");
                }
                break;
            case "PriceSmaCrossover":
                strategy = new PriceSmaCrossover(exchange, exchange.getBook(stockName), 14);
                break;
            case "SimpleRSI":
                try {
                    strategy = new SimpleRSI(exchange.getBook(stockName));
                } catch (NotEnoughDataException ex) {
                    MessageBox.infoBox("Insufficient Data to create Simple RSI Strategy", "");
                }
                break;
            case "Simple_MACD_ADX":
                try {
                    strategy = new Simple_MACD_ADX(exchange.getBook(stockName));
                } catch (NotEnoughDataException ex) {
                    MessageBox.infoBox("Insufficient Data to create Simple MACD ADX Strategy", "");
                }
                break;
            default:
                MessageBox.infoBox("Strategy does not exist.", "Strategy not found");
                return;
        }
        try {
            MarketParticipant participant = new MarketParticipant(partName, ID, exchange, stockName, strategy);

            participants.add(participant);

            DefaultListModel model = new DefaultListModel();

            for (MarketParticipant part : participants) {
                model.addElement(part.toString());
            }

            lbxParticipantList.setModel(model);

        } catch (NotEnoughDataException ex) {
            MessageBox.infoBox("Market Participant not created.", "Not enough data");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnGenerateParticipants1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateParticipants1ActionPerformed
        lbxParticipantList.setModel(new DefaultListModel());
        participants.clear();
        btnGenerateParticipants.setEnabled(true);
    }//GEN-LAST:event_btnGenerateParticipants1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Participants.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Participants.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Participants.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Participants.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Participants().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerateParticipants;
    private javax.swing.JButton btnGenerateParticipants1;
    private javax.swing.JComboBox cbxStocks;
    private javax.swing.JComboBox cbxStrategies;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lbxParticipantList;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
